### ISSUE TITLE
SyntaxError: Cannot declare a let variable twice: 'y'.

### ISSUE THREAD

**Issue by marcolindner** [jdiemke/AISA#1]
Mobile Safari iOS 10.3.3 Line 1456

**Comment by jdiemke** [comment]
Very interesting. Firefox and Chrome allow shadowing of function parameters using let variables (tested on windows and linux). tsc does not complain about that during compilation as well. The let  keyword inside a for loop is block scoped. Seems this is a Safair Bug:

> Fixed a syntax error thrown when declaring a top level for-loop iteration variable the same as a function parameter

Here is the reference to the Bugticket:
[https://bugs.webkit.org/show_bug.cgi?id=171041](https://bugs.webkit.org/show_bug.cgi?id=171041)**
